const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            image: '/images/shirt1.jpg',
            banner: '/images/banner1.jpg',
            price: 70,
            brand: 'Nike',
            description: 'A popular shirt',
            category: 'Shirts',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
        },
        {
            name: 'Stylish Jacket',
            slug: 'stylish-jacket',
            image: '/images/pants1.jpg',
            banner: '/images/banner2.jpg',
            price: 120,
            brand: 'Adidas',
            description: 'A trendy jacket for all seasons',
            category: 'Jackets',
            rating: 4.7,
            numReviews: 15,
            countInStock: 10,
        },
        {
            name: 'Running Shoes',
            slug: 'running-shoes',
            image: '/images/pants2.jpg',
            banner: '/images/banner3.jpg',
            price: 90,
            brand: 'Puma',
            description: 'Comfortable shoes for running',
            category: 'Shoes',
            rating: 4.3,
            numReviews: 22,
            countInStock: 30,
        },
        {
            name: 'Classic Hat',
            slug: 'classic-hat',
            image: '/images/pants3.jpg',
            banner: '/images/banner4.jpg',
            price: 25,
            brand: 'New Era',
            description: 'A classic hat for everyday wear',
            category: 'Accessories',
            rating: 4.8,
            numReviews: 9,
            countInStock: 50,
        },
        {
            name: 'Casual Pants',
            slug: 'casual-pants',
            image: '/images/shirt2.jpg',
            banner: '/images/banner2.jpg',
            price: 60,
            brand: 'Levi\'s',
            description: 'Comfortable pants for casual outings',
            category: 'Pants',
            rating: 4.4,
            numReviews: 18,
            countInStock: 25,
        },
        {
            name: 'Elegant Dress',
            slug: 'elegant-dress',
            image: '/images/shirt3.jpg',
            banner: '/images/banner6.jpg',
            price: 150,
            brand: 'Gucci',
            description: 'An elegant dress for special occasions',
            category: 'Dresses',
            rating: 4.9,
            numReviews: 12,
            countInStock: 8,
        },
        {
            name: 'Sports Watch',
            slug: 'sports-watch',
            image: '/images/shirt1.jpg',
            banner: '/images/banner2.jpg',
            price: 200,
            brand: 'Garmin',
            description: 'A durable watch for sports enthusiasts',
            category: 'Watches',
            rating: 4.6,
            numReviews: 20,
            countInStock: 15,
        },
        {
            name: 'Fitness Tracker',
            slug: 'fitness-tracker',
            image: '/images/pants1.jpg',
            banner: '/images/banner8.jpg',
            price: 110,
            brand: 'Fitbit',
            description: 'Track your fitness with this reliable device',
            category: 'Fitness',
            rating: 4.2,
            numReviews: 30,
            countInStock: 40,
        },
        {
            name: 'Leather Wallet',
            slug: 'leather-wallet',
            image: '/images/pants3.jpg',
            banner: '/images/banner9.jpg',
            price: 45,
            brand: 'Fossil',
            description: 'A stylish leather wallet with multiple compartments',
            category: 'Accessories',
            rating: 4.5,
            numReviews: 25,
            countInStock: 35,
        },

    ]
}

export default data
